### ISSUE TITLE
Typo in subnet mask for /31 subnets

### ISSUE THREAD

**Issue by imiddleton1** [ericpskl/unTun365#1]
I just noticed in your code that for /31 subnets you have 255.255.254.254 (Line 60).

It should be 255.255.255.254.

254.254 causes errors in OpenVPN when you try to use those routes.

**Comment by ericpskl** [comment]
Thanks! I've updated the code with the correct subnet mask.

**Comment by imiddleton1** [comment]
That was quick!  Thanks for this script BTW.  Exactly what I was looking for.

I ended up stripping off the -- and adding the routes to the client config file and they work there as well.

**Comment by ericpskl** [comment]
You're welcome -- glad that the code has been useful!
